version: '3'
services:
  postgres:
    image: postgres:14
    ports:
      - 127.0.0.1:5432:5432/tcp
    environment:
      - POSTGRES_PASSWORD=deployments
      - POSTGRES_USER=deployments
      - POSTGRES_DB=deployments
    restart: always
  redis:
    image: redis:6
    command: redis-server --requirepass deployments
    ports:
      - 127.0.0.1:6379:6379/tcp
    restart: always
