version: '3.5'
services:
  mariadb:
    image: mariadb:10
    environment:
      - MARIADB_ROOT_PASSWORD=test
      - MARIADB_PASSWORD=test
      - MARIADB_USER=test
      - MARIADB_DATABASE=test
    restart: always
  postgres:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    networks:
      - integration
  redis:
    image: redis:6
    command: redis-server --requirepass test
    networks:
      - integration

networks:
  integration:
    name: ${NETWORK_NAME}